# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pedra.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pedra.proto',
  package='pedraPapelTesoura',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bpedra.proto\x12\x11pedraPapelTesoura\"d\n\x06Jogada\x12,\n\x08simbolo1\x18\x01 \x01(\x0e\x32\x1a.pedraPapelTesoura.Simbolo\x12,\n\x08simbolo2\x18\x02 \x01(\x0e\x32\x1a.pedraPapelTesoura.Simbolo\"8\n\x08Resposta\x12,\n\x08vencedor\x18\x01 \x01(\x0e\x32\x1a.pedraPapelTesoura.Simbolo*,\n\x07Simbolo\x12\t\n\x05PEDRA\x10\x00\x12\t\n\x05PAPEL\x10\x01\x12\x0b\n\x07TESOURA\x10\x02\x32J\n\x07Partida\x12?\n\x05Jogar\x12\x19.pedraPapelTesoura.Jogada\x1a\x1b.pedraPapelTesoura.Respostab\x06proto3'
)

_SIMBOLO = _descriptor.EnumDescriptor(
  name='Simbolo',
  full_name='pedraPapelTesoura.Simbolo',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PEDRA', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PAPEL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TESOURA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=194,
  serialized_end=238,
)
_sym_db.RegisterEnumDescriptor(_SIMBOLO)

Simbolo = enum_type_wrapper.EnumTypeWrapper(_SIMBOLO)
PEDRA = 0
PAPEL = 1
TESOURA = 2



_JOGADA = _descriptor.Descriptor(
  name='Jogada',
  full_name='pedraPapelTesoura.Jogada',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='simbolo1', full_name='pedraPapelTesoura.Jogada.simbolo1', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simbolo2', full_name='pedraPapelTesoura.Jogada.simbolo2', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=134,
)


_RESPOSTA = _descriptor.Descriptor(
  name='Resposta',
  full_name='pedraPapelTesoura.Resposta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vencedor', full_name='pedraPapelTesoura.Resposta.vencedor', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=192,
)

_JOGADA.fields_by_name['simbolo1'].enum_type = _SIMBOLO
_JOGADA.fields_by_name['simbolo2'].enum_type = _SIMBOLO
_RESPOSTA.fields_by_name['vencedor'].enum_type = _SIMBOLO
DESCRIPTOR.message_types_by_name['Jogada'] = _JOGADA
DESCRIPTOR.message_types_by_name['Resposta'] = _RESPOSTA
DESCRIPTOR.enum_types_by_name['Simbolo'] = _SIMBOLO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Jogada = _reflection.GeneratedProtocolMessageType('Jogada', (_message.Message,), {
  'DESCRIPTOR' : _JOGADA,
  '__module__' : 'pedra_pb2'
  # @@protoc_insertion_point(class_scope:pedraPapelTesoura.Jogada)
  })
_sym_db.RegisterMessage(Jogada)

Resposta = _reflection.GeneratedProtocolMessageType('Resposta', (_message.Message,), {
  'DESCRIPTOR' : _RESPOSTA,
  '__module__' : 'pedra_pb2'
  # @@protoc_insertion_point(class_scope:pedraPapelTesoura.Resposta)
  })
_sym_db.RegisterMessage(Resposta)



_PARTIDA = _descriptor.ServiceDescriptor(
  name='Partida',
  full_name='pedraPapelTesoura.Partida',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=240,
  serialized_end=314,
  methods=[
  _descriptor.MethodDescriptor(
    name='Jogar',
    full_name='pedraPapelTesoura.Partida.Jogar',
    index=0,
    containing_service=None,
    input_type=_JOGADA,
    output_type=_RESPOSTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARTIDA)

DESCRIPTOR.services_by_name['Partida'] = _PARTIDA

# @@protoc_insertion_point(module_scope)
