# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pedra_pb2 as pedra__pb2


class PartidaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Jogar = channel.unary_unary(
                '/pedraPapelTesoura.Partida/Jogar',
                request_serializer=pedra__pb2.Jogada.SerializeToString,
                response_deserializer=pedra__pb2.Resposta.FromString,
                )


class PartidaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Jogar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartidaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Jogar': grpc.unary_unary_rpc_method_handler(
                    servicer.Jogar,
                    request_deserializer=pedra__pb2.Jogada.FromString,
                    response_serializer=pedra__pb2.Resposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pedraPapelTesoura.Partida', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Partida(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Jogar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pedraPapelTesoura.Partida/Jogar',
            pedra__pb2.Jogada.SerializeToString,
            pedra__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
